name: Build Android and run Maestro tests

on:
  workflow_dispatch:

jobs:
  build_release:
    name: Build Android Example App and run Maestro tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2

      - name: Install npm dependencies (bun)
        run: bun install
      - name: Install npm dependencies in example/ (bun)
        working-directory: example
        run: bun install

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
          java-package: jdk

      - name: Run Gradle Build for example/android/
        working-directory: example
        run: bun run build:android-release
      
      - name: Run Maestro tests
        working-directory: example
        run: bun run maestro test

      
    
